# Generated by Django 3.1.2 on 2020-10-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201011_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
    ]
