# Generated by Django 3.1.2 on 2020-10-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
